#!/bin/sh

# Exit on error
set -o errexit

while getopts ":d:h:p:f:" option; do
    case "${option}" in
        d)
            db_name=${OPTARG}
            ;;
        f)
            file=${OPTARG}
            ;;
        *)
            exit 3
            ;;
    esac
done
shift $((OPTIND-1))

pg_cmd='psql --set ON_ERROR_STOP=true postgresql://postgres@localhost/'

$pg_cmd -q -c "select pg_terminate_backend(pid) from pg_stat_activity where datname='$db_name';"

$pg_cmd -q -c "drop database if exists $db_name;"

$pg_cmd -q -c "create database $db_name;"

#$pg_cmd --dbname="$db_name" -f "$file"
psql --set ON_ERROR_STOP=true "postgresql://postgres@localhost/$db_name" -f "$file"

